name: gjol_app
description: "gjoldb.info的APP版本"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.1
  webview_flutter_android: ^4.10.5
  network_info_plus: ^4.0.0
  device_info_plus: ^10.0.0
  permission_handler: ^11.0.0
  crypto: ^3.0.3
  encrypt: ^5.0.1
  convert: ^3.1.1
  flutter_secure_storage: ^4.2.1
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  openapi_generator: ^6.1.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.dev
    - .env.prod

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

